// js/species.js — 台北市行道樹樹種資料（台北市112年規範附件五，229種）
// code: 樹種編碼（附件五）, origin: 原生/外來, aliases/traits: 豐富資料（25種常見樹）

const SPECIES_INFO = {
  '榕樹': {
    code: 1, origin: '原生',
    aliases: ['正榕', '島榕', '鳥榕'],
    traits: '常綠大喬木，樹幹粗壯，老樹常生氣生根形成壯觀的氣根簾。葉革質深綠，全年常綠。耐熱耐旱，遮蔭效果絕佳，是台灣最常見的行道樹。',
  },
  '樟樹': {
    code: 2, origin: '原生',
    aliases: ['本樟', '香樟', '烏樟'],
    traits: '台灣原生常綠大喬木，葉互生，揉碎有濃烈樟腦香氣。春季開淡黃小花，秋冬結黑色球形漿果。壽命可達數百年，是台北最常見的行道樹之一。',
  },
  '茄苳': { code: 3, origin: '原生' },
  '臺灣欒樹': { code: 4, origin: '原生' },
  '白千層': {
    code: 5, origin: '外來',
    aliases: ['千層皮', '玉樹'],
    traits: '常綠喬木，樹皮白色，可一層層剝落，故名「白千層」。葉片細長，全株具香氣。夏秋開乳白色穗狀花序，對空氣污染耐受力強。',
  },
  '楓香': {
    code: 6, origin: '原生',
    aliases: ['楓樹', '香楓'],
    traits: '台灣原生落葉大喬木，葉掌狀三裂，秋冬轉橙紅後落葉，是台灣少數有明顯秋色的樹種。春季開球形小花，果實為帶刺球形聚合果。',
  },
  '黑板樹': {
    code: 7, origin: '外來',
    aliases: ['象皮樹', '燈架樹'],
    traits: '常綠大喬木，枝條輪生整齊如燈架。葉片革質深綠，富含白色乳汁。生長快速，秋冬開花，花有特殊氣味。為台北常見校園及行道樹。',
  },
  '小葉欖仁': { code: 8, origin: '外來' },
  '大花紫薇': { code: 9, origin: '外來' },
  '水黃皮': {
    code: 10, origin: '原生',
    aliases: ['九重吹', '水流豆'],
    traits: '台灣原生常綠喬木，耐鹽耐濕，為優良的海岸及行道樹種。羽狀複葉亮綠，秋冬開淡紫色蝶形花。果實豆莢狀，種子具毒性。',
  },
  '木棉': {
    code: 11, origin: '外來',
    aliases: ['英雄樹', '斑芝棉', '攀枝花'],
    traits: '落葉大喬木，樹幹筆直有瘤刺。每年2至3月先花後葉，開紅橙色大型杯狀花，極為壯觀。蒴果成熟後裂開，棉絮隨風飄散。',
  },
  '菩提樹': { code: 12, origin: '外來' },
  '盾柱木': { code: 13, origin: '外來' },
  '大王椰子': { code: 14, origin: '外來' },
  '榔榆': {
    code: 15, origin: '原生',
    aliases: ['小葉榆', '秋榆'],
    traits: '落葉或半落葉喬木，葉小，邊緣鋸齒明顯。樹皮老後剝落呈斑駁狀，形似迷彩。秋季開小花，翅果橢圓形。耐修剪，常作行道樹。',
  },
  '垂榕': { code: 16, origin: '外來' },
  '苦楝': {
    code: 17, origin: '原生',
    aliases: ['楝樹', '苦苓'],
    traits: '台灣原生落葉喬木，春季嫩葉與淡紫色小花同時盛開，花有淡香。核果橢圓形，冬季黃熟留枝，是八哥等鳥類重要食物來源。',
  },
  '刺桐': { code: 18, origin: '原生' },
  '蒲葵': {
    code: 19, origin: '原生',
    aliases: ['扇葉葵', '中國蒲葵'],
    traits: '常綠棕櫚科喬木，葉片大型扇形，可達1.5公尺寬。樹形挺拔，耐熱耐旱，常見於公園及行道。果實小橢圓形，成熟時藍黑色。',
  },
  '山櫻花': { code: 20, origin: '原生' },
  '阿勃勒': {
    code: 21, origin: '外來',
    aliases: ['波斯皂莢', '黃金雨', '臘腸樹'],
    traits: '落葉喬木，原產南亞。每年5至6月開滿下垂的金黃色總狀花序，有「黃金雨」美譽。果實圓筒形如臘腸，長可達60公分。',
  },
  '烏桕': { code: 22, origin: '原生' },
  '紫薇': { code: 23, origin: '外來' },
  '光蠟樹': { code: 24, origin: '原生' },
  '橡皮樹': { code: 25, origin: '外來' },
  '美人樹': {
    code: 26, origin: '外來',
    aliases: ['酒瓶木棉', '美人棉'],
    traits: '落葉喬木，樹幹基部膨大如酒瓶，幼樹樹幹有粗刺。秋冬開粉紅至桃紅色大花，與木棉同屬木棉科。蒴果成熟後裂出白色棉絮。',
  },
  '火燄木': { code: 27, origin: '外來' },
  '羅比親王海棗': { code: 28, origin: '外來' },
  '檬果': { code: 29, origin: '原生' },
  '印度紫檀': {
    code: 30, origin: '外來',
    aliases: ['薔薇木', '紫檀'],
    traits: '半落葉大喬木，原產印度、東南亞。夏季開黃色蝶形花，有香氣。木材心材深紅色，是名貴木材。耐熱耐污染，為優良行道樹。',
  },
  '香楠': { code: 31, origin: '原生' },
  '豔紫荊': { code: 32, origin: '外來' },
  '桃花心木': { code: 33, origin: '外來' },
  '龍柏': { code: 34, origin: '原生' },
  '風鈴木': { code: 35, origin: '外來' },
  '鳳凰木': {
    code: 36, origin: '外來',
    aliases: ['火焰木', '金鳳花樹'],
    traits: '落葉大喬木，原產馬達加斯加。每年5至7月開滿鮮紅橙色大花，豔麗如火焰。羽狀複葉細緻，樹形寬闊，夏季遮蔭效果極佳。',
  },
  '臺灣櫸': { code: 37, origin: '原生' },
  '杜英': { code: 38, origin: '原生' },
  '猢猻木': { code: 39, origin: '外來' },
  '無患子': { code: 40, origin: '原生' },
  '大葉桉': { code: 41, origin: '外來' },
  '福木': {
    code: 42, origin: '原生',
    aliases: ['福樹', '菲島福木'],
    traits: '常綠小喬木，葉片厚革質深綠，樹形整齊。果實圓形，成熟時橙黃色，富含樹脂。耐鹽耐旱，為優良海岸防風及行道樹種。',
  },
  '大葉山欖': { code: 43, origin: '原生' },
  '九芎': { code: 44, origin: '原生' },
  '烏心石': { code: 45, origin: '原生' },
  '厚皮香': { code: 46, origin: '原生' },
  '青楓': { code: 47, origin: '原生' },
  '黃連木': { code: 48, origin: '原生' },
  '欖仁': { code: 49, origin: '原生' },
  '鐵刀木': {
    code: 50, origin: '外來',
    aliases: ['黑心木', '泰國蝴蝶', '暹羅決明'],
    traits: '常綠喬木，原產熱帶亞洲。夏秋開黃色蝶形花，豆莢細長扁平。木材黑褐色堅硬，為珍貴用材。耐熱耐旱，常作行道樹。',
  },
  '羅漢松': { code: 51, origin: '外來' },
  '錫蘭橄欖': { code: 52, origin: '外來' },
  '槭葉翅子木': { code: 53, origin: '外來' },
  '蠟腸樹': { code: 54, origin: '外來' },
  '馬拉巴栗': { code: 55, origin: '外來' },
  '臺灣海棗': { code: 56, origin: '原生' },
  '構樹': { code: 57, origin: '原生' },
  '第倫桃': { code: 58, origin: '外來' },
  '羊蹄甲': {
    code: 59, origin: '外來',
    aliases: ['洋紫荊', '豬蹄花'],
    traits: '常綠小喬木，葉先端二裂形似羊蹄。秋至春季開粉紅至紫色花朵，花期長。樹形優美，常作為公園及行道樹種植。',
  },
  '木麻黃': { code: 60, origin: '外來' },
  '臺灣赤楠': { code: 61, origin: '原生' },
  '流蘇': { code: 62, origin: '原生' },
  '濕地松': { code: 63, origin: '外來' },
  '楊梅': { code: 64, origin: '原生' },
  '稜果榕': { code: 65, origin: '原生' },
  '青剛櫟': { code: 66, origin: '原生' },
  '雀榕': { code: 67, origin: '原生' },
  '蓮霧': { code: 68, origin: '外來' },
  '紅楠': { code: 69, origin: '原生' },
  '柳樹': { code: 70, origin: '外來' },
  '華盛頓椰子': { code: 71, origin: '外來' },
  '黃椰子': { code: 72, origin: '外來' },
  '緬梔': { code: 73, origin: '外來' },
  '洋玉蘭': { code: 74, origin: '外來' },
  '小葉南洋杉': { code: 75, origin: '外來' },
  '龍眼樹': { code: 76, origin: '外來' },
  '落羽松': { code: 77, origin: '外來' },
  '棍棒椰子': { code: 78, origin: '外來' },
  '肯氏南洋杉': { code: 79, origin: '外來' },
  '臺灣海桐': { code: 80, origin: '原生' },
  '玉蘭': { code: 81, origin: '外來' },
  '麵包樹': { code: 82, origin: '外來' },
  '檳榔': { code: 83, origin: '外來' },
  '黃槐': { code: 84, origin: '外來' },
  '朴樹': { code: 85, origin: '原生' },
  '大葉楠': { code: 86, origin: '原生' },
  '石栗': { code: 87, origin: '原生' },
  '亞歷山大椰子': { code: 88, origin: '外來' },
  '桑樹': { code: 89, origin: '原生' },
  '金龜樹': { code: 90, origin: '外來' },
  '臺灣肖楠': { code: 91, origin: '原生' },
  '油桐': { code: 92, origin: '外來' },
  '酒瓶椰子': { code: 93, origin: '外來' },
  '合歡': { code: 94, origin: '外來' },
  '血桐': { code: 95, origin: '原生' },
  '芭樂': { code: 96, origin: '外來' },
  '黑松': { code: 97, origin: '外來' },
  '楊桃': { code: 98, origin: '外來' },
  '臺灣石楠': { code: 99, origin: '原生' },
  '桃樹': { code: 100, origin: '外來' },
  '澳州鴨腳木': { code: 101, origin: '外來' },
  '紅千層': { code: 102, origin: '外來' },
  '爪哇旃那': { code: 103, origin: '外來' },
  '琴葉榕': { code: 104, origin: '外來' },
  '檸檬桉': { code: 105, origin: '外來' },
  '桂花': { code: 106, origin: '外來' },
  '扁柏': { code: 107, origin: '原生' },
  '銀樺': { code: 108, origin: '外來' },
  '巨葉榕': { code: 109, origin: '外來' },
  '李樹': { code: 110, origin: '外來' },
  '孔雀椰子': { code: 111, origin: '外來' },
  '波羅蜜': { code: 112, origin: '外來' },
  '肉桂': { code: 113, origin: '原生' },
  '山陀兒': { code: 114, origin: '外來' },
  '八重櫻': { code: 115, origin: '原生' },
  '掌葉蘋婆': { code: 116, origin: '外來' },
  '臺灣三角楓': { code: 117, origin: '原生' },
  '樹蘭': { code: 118, origin: '外來' },
  '山黃麻': { code: 119, origin: '原生' },
  '饅頭果': { code: 120, origin: '原生' },
  '裡白蔥木': { code: 121, origin: '原生' },
  '槭樹': { code: 122, origin: '外來' },
  '黃槿': { code: 123, origin: '原生' },
  '相思樹': { code: 124, origin: '原生' },
  '破布子': { code: 125, origin: '原生' },
  '竹柏': { code: 126, origin: '原生' },
  '印度黃檀': { code: 127, origin: '外來' },
  '軟毛柿': { code: 128, origin: '原生' },
  '海檬果': { code: 129, origin: '原生' },
  '臺東漆': { code: 130, origin: '原生' },
  '楊桐': { code: 131, origin: '原生' },
  '洋紫荊': {
    code: 132, origin: '外來',
    aliases: ['紫荊花', '香港蘭', '南洋紫荊'],
    traits: '常綠小喬木，葉頂端二裂如牛蹄，故又名「羊蹄甲」。秋冬至春季開粉紫色花，5瓣中4瓣較大、1瓣有紫色條紋。全年幾乎不間斷開花。',
  },
  '孔雀木': { code: 133, origin: '外來' },
  '蒲姜木': { code: 134, origin: '原生' },
  '肯氏蒲桃': { code: 135, origin: '外來' },
  '岩海棗': { code: 136, origin: '外來' },
  '金平氏冬青': { code: 137, origin: '原生' },
  '枇杷': { code: 138, origin: '外來' },
  '香椿': { code: 139, origin: '外來' },
  '銀合歡': { code: 140, origin: '外來' },
  '咖啡樹': { code: 141, origin: '外來' },
  '七里香': { code: 142, origin: '原生' },
  '柑橘': { code: 143, origin: '外來' },
  '二葉松': { code: 144, origin: '原生' },
  '鐵冬青': { code: 145, origin: '原生' },
  '鵝掌柴': { code: 146, origin: '原生' },
  '柚子': { code: 147, origin: '外來' },
  '雨豆樹': {
    code: 148, origin: '外來',
    aliases: ['雨樹', '陰雨樹'],
    traits: '常綠大喬木，樹冠寬廣如巨傘，可達20公尺以上。傍晚或下雨前葉片會閉合，故名「雨豆樹」。夏季開粉紅色絨球狀花序，觀賞價值高。',
  },
  '九重葛': { code: 149, origin: '外來' },
  '椰子': {
    code: 150, origin: '外來',
    aliases: ['可可椰子', '椰棗'],
    traits: '常綠棕櫚科大喬木，樹幹筆直有環狀葉痕。葉片羽狀複葉，長可達5公尺。果實即椰子，富含椰汁與椰肉。常見於海岸及公園。',
  },
  '大葉合歡': { code: 151, origin: '外來' },
  '水柳': { code: 152, origin: '原生' },
  '梅': { code: 153, origin: '外來' },
  '絨果決明': { code: 154, origin: '外來' },
  '大葉桃花心木': { code: 155, origin: '外來' },
  '含笑花': { code: 156, origin: '外來' },
  '吉野櫻': { code: 157, origin: '外來' },
  '島榕': { code: 158, origin: '原生' },
  '柚木': { code: 159, origin: '外來' },
  '木槿': { code: 160, origin: '外來' },
  '夾竹桃': { code: 161, origin: '外來' },
  '日日櫻': { code: 162, origin: '外來' },
  '土肉桂': { code: 163, origin: '原生' },
  '黃花風鈴木': { code: 164, origin: '外來' },
  '羅望子': { code: 165, origin: '外來' },
  '魚木': { code: 166, origin: '原生' },
  '黃鐘花': { code: 167, origin: '外來' },
  '陰香': { code: 168, origin: '外來' },
  '酪梨': { code: 169, origin: '外來' },
  '蛋黃果': { code: 170, origin: '外來' },
  '黃果垂榕': { code: 171, origin: '外來' },
  '山茶花': { code: 172, origin: '外來' },
  '銀杏': { code: 173, origin: '外來' },
  '藍花楹': { code: 174, origin: '外來' },
  '雞冠刺桐': { code: 175, origin: '外來' },
  '洋紅風鈴木': { code: 176, origin: '外來' },
  '黃脈刺桐': { code: 177, origin: '外來' },
  '富士櫻': { code: 178, origin: '外來' },
  '澀葉榕': { code: 179, origin: '原生' },
  '香龍血樹': { code: 180, origin: '外來' },
  '南洋含笑花': { code: 181, origin: '外來' },
  '黃蝴蝶': { code: 182, origin: '外來' },
  '辣木': { code: 183, origin: '外來' },
  '野梨': { code: 184, origin: '原生' },
  '蘭嶼肉桂': { code: 185, origin: '原生' },
  '加羅林魚木': { code: 186, origin: '外來' },
  '柳丁': { code: 187, origin: '外來' },
  '珊瑚刺桐': { code: 188, origin: '外來' },
  '毛魚臭木': { code: 189, origin: '原生' },
  '森氏紅淡比': { code: 190, origin: '原生' },
  '安石榴': { code: 191, origin: '外來' },
  '臭娘子': { code: 192, origin: '原生' },
  '白木香': { code: 193, origin: '外來' },
  '南洋馬蹄花': { code: 194, origin: '外來' },
  '橘子': { code: 195, origin: '外來' },
  '檸檬': { code: 196, origin: '外來' },
  '荔枝': { code: 197, origin: '外來' },
  '五葉松': { code: 198, origin: '原生' },
  '栗豆樹': { code: 199, origin: '外來' },
  '寒櫻': { code: 200, origin: '外來' },
  '瓊崖海棠': { code: 201, origin: '原生' },
  '串錢柳': { code: 202, origin: '外來' },
  '女王椰子': { code: 203, origin: '外來' },
  '臺灣油杉': { code: 204, origin: '原生' },
  '蘭嶼烏心石': { code: 205, origin: '原生' },
  '千頭木麻黃': { code: 206, origin: '外來' },
  '珊瑚樹': { code: 207, origin: '原生' },
  '山柿': { code: 208, origin: '原生' },
  '小梗木薑子': { code: 209, origin: '原生' },
  '賽赤楠': { code: 210, origin: '原生' },
  '西印度櫻桃': { code: 211, origin: '外來' },
  '柿子': { code: 212, origin: '外來' },
  '馬尼拉欖仁': { code: 213, origin: '外來' },
  '釋迦': { code: 214, origin: '外來' },
  '垂柳': {
    code: 215, origin: '外來',
    aliases: ['楊柳', '清明柳', '絲柳'],
    traits: '落葉喬木，枝條細長下垂，隨風搖曳，姿態優美。常種植於水邊。春季開細小花序，種子附白色棉毛隨風飄散。',
  },
  '黃金榕': { code: 216, origin: '外來' },
  '金剛纂': { code: 217, origin: '外來' },
  '河津櫻': { code: 218, origin: '外來' },
  '水同木': { code: 219, origin: '原生' },
  '昭和櫻': { code: 220, origin: '外來' },
  '香水樹': { code: 221, origin: '外來' },
  '中東海棗': { code: 222, origin: '外來' },
  '凍子椰子': { code: 223, origin: '外來' },
  '亞里垂榕': { code: 224, origin: '外來' },
  '蒲桃': { code: 225, origin: '外來' },
  '蘭嶼羅漢松': { code: 226, origin: '原生' },
  '石朴': { code: 227, origin: '原生' },
  '黃玉蘭': { code: 228, origin: '外來' },
  '海南菜豆樹': { code: 229, origin: '外來' },
};

/**
 * 根據樹種名稱查詢資料（含編碼、原生/外來、別名、性狀）
 */
function getSpeciesInfo(speciesName) {
  if (!speciesName) return null;
  return SPECIES_INFO[speciesName] || null;
}

/**
 * 回傳所有樹種名稱清單（供 datalist 搜尋用）
 */
function getSpeciesNames() {
  return Object.keys(SPECIES_INFO);
}
